--[[
Barcode scanning.

Rather than handing original files to the decoder (which cannot read RAW), each
photo is rendered to a JPEG by Lightroom via requestJpegThumbnail. That works for
every format Lightroom supports, including virtual copies, and respects crops.
The JPEGs are written to a temp folder and decoded in batches by ZXingReader.

Previews are fast but small, and fine 1D barcodes (e.g. a Code 128 on a subject
card) need more pixels than a QR code. So photos where the preview pass finds
anything can be rescanned from a full-resolution render via LrExportSession.
]]

local LrDate = import 'LrDate'
local LrExportSession = import 'LrExportSession'
local LrFileUtils = import 'LrFileUtils'
local LrLogger = import 'LrLogger'
local LrPathUtils = import 'LrPathUtils'
local LrTasks = import 'LrTasks'

local ReaderOutput = require 'ReaderOutput'

local logger = LrLogger('LrCBarcodes')
logger:enable('logfile')

local Scanner = {}

Scanner.batchSize = 16

Scanner.STATUS_FOUND = "Found"
Scanner.STATUS_NOT_FOUND = "Not Found"
Scanner.STATUS_ERROR = "Read Error"

local readerPath = LrPathUtils.child(LrPathUtils.child(LrPathUtils.child(_PLUGIN.path, 'bin'), 'win'),
                                     'ZXingReader.exe')

-- Returns nil if scanning can run on this system, otherwise a message explaining why not.
function Scanner.checkAvailable()
    if not WIN_ENV then
        return "LrC Barcodes currently supports Windows only."
    end
    if not LrFileUtils.exists(readerPath) then
        return "The barcode reader is missing from the plug-in folder:\n" .. readerPath
    end
    return nil
end

function Scanner.createWorkDir()
    local base = LrPathUtils.child(LrPathUtils.getStandardFilePath('temp'), 'LrCBarcodes')
    local dir = LrFileUtils.chooseUniqueFileName(base)
    LrFileUtils.createAllDirectories(dir)
    return dir
end

-- Renders JPEG previews for all photos in a batch concurrently.
-- Sets job.data (JPEG bytes) or leaves it nil on failure.
local function renderPreviews(jobs, size)
    for _, job in ipairs(jobs) do
        -- Keep a reference to the request object; if it is garbage collected
        -- the request is cancelled. The callback may fire more than once as a
        -- better preview becomes available, so keep the latest image.
        job.request = job.photo:requestJpegThumbnail(size, size, function(data, errorMessage)
            if data then
                job.data = data
            elseif errorMessage then
                job.error = errorMessage
            end
            job.done = true
        end)
    end

    local deadline = LrDate.currentTime() + 15 + 5 * #jobs
    while LrDate.currentTime() < deadline do
        local allDone = true
        for _, job in ipairs(jobs) do
            if not job.done then
                allDone = false
                break
            end
        end
        if allDone then
            break
        end
        LrTasks.sleep(0.05)
    end
    -- Short grace period for any follow-up (higher resolution) callbacks.
    LrTasks.sleep(0.2)

    for _, job in ipairs(jobs) do
        job.request = nil
    end
end

local function runReader(dir, fileNames)
    local outPath = LrPathUtils.child(dir, 'reader-output.txt')
    local errPath = LrPathUtils.child(dir, 'reader-errors.txt')
    LrFileUtils.delete(outPath)
    LrFileUtils.delete(errPath)

    -- File names are generated by us (no spaces), and the reader runs inside the
    -- work dir so its output lines start with those short names.
    local command = string.format('cd /d "%s" && "%s" -1 %s >"%s" 2>"%s"',
                                  dir, readerPath, table.concat(fileNames, " "), outPath, errPath)
    -- cmd.exe strips the outermost pair of quotes, so wrap the whole command.
    local exitCode = LrTasks.execute('"' .. command .. '"')

    local output = LrFileUtils.exists(outPath) and LrFileUtils.readFile(outPath) or ""
    local errors = LrFileUtils.exists(errPath) and LrFileUtils.readFile(errPath) or ""
    if errors ~= "" then
        logger:warn("ZXingReader (exit " .. tostring(exitCode) .. "): " .. errors)
    end
    return ReaderOutput.parse(output)
end

-- Renders full-size JPEGs through an export session. Sets job.path on success.
local function renderFullSize(jobs, dir)
    local exportDir = LrPathUtils.child(dir, 'export')
    LrFileUtils.createAllDirectories(exportDir)

    local photos, jobsByPhoto = {}, {}
    for _, job in ipairs(jobs) do
        table.insert(photos, job.photo)
        jobsByPhoto[job.photo] = job
    end

    local session = LrExportSession {
        photosToExport = photos,
        exportSettings = {
            LR_format = 'JPEG',
            LR_jpeg_quality = 0.9,
            LR_export_colorSpace = 'sRGB',
            LR_size_doConstrain = false,
            LR_outputSharpeningOn = false,
            LR_minimizeEmbeddedMetadata = true,
            LR_removeLocationMetadata = true,
            LR_useWatermark = false,
            LR_includeVideoFiles = false,
            LR_export_destinationType = 'specificFolder',
            LR_export_destinationPathPrefix = exportDir,
            LR_export_useSubfolder = false,
            LR_collisionHandling = 'rename',
            LR_reimportExportedPhoto = false,
        },
    }

    for _, rendition in session:renditions() do
        local job = jobsByPhoto[rendition.photo]
        local ok, pathOrMessage = rendition:waitForRender()
        if job then
            if ok then
                -- Exported names can contain spaces; the reader needs our short names.
                local path = LrPathUtils.child(dir, job.fileName)
                LrFileUtils.delete(path)
                if LrFileUtils.move(pathOrMessage, path) then
                    job.path = path
                else
                    job.error = "Could not move full-size render"
                    LrFileUtils.delete(pathOrMessage)
                end
            else
                job.error = "Full-size render failed: " .. tostring(pathOrMessage)
            end
        elseif ok then
            LrFileUtils.delete(pathOrMessage)
        end
    end
end

-- Writes preview JPEG data to disk. Sets job.path on success.
local function writePreviews(jobs, dir)
    for _, job in ipairs(jobs) do
        if job.data then
            local path = LrPathUtils.child(dir, job.fileName)
            local file = io.open(path, "wb")
            if file then
                file:write(job.data)
                file:close()
                job.path = path
            else
                job.error = "Could not write temporary file " .. path
            end
            job.data = nil
        end
    end
end

local function decodeJobs(jobs, dir, missingMessage)
    local fileNames = {}
    for _, job in ipairs(jobs) do
        if job.path then
            table.insert(fileNames, job.fileName)
        end
    end

    local parsed = {}
    if #fileNames > 0 then
        parsed = runReader(dir, fileNames)
    end

    local results = {}
    for i, job in ipairs(jobs) do
        local result
        if not job.path then
            result = { status = Scanner.STATUS_ERROR, barcodes = {},
                       message = job.error or missingMessage }
        else
            local entry = parsed[job.fileName]
            if not entry then
                result = { status = Scanner.STATUS_ERROR, barcodes = {},
                           message = "The barcode reader could not open the image" }
            elseif #entry.barcodes > 0 then
                result = { status = Scanner.STATUS_FOUND, barcodes = entry.barcodes }
            elseif #entry.errors > 0 then
                -- A barcode was located but could not be decoded.
                result = { status = Scanner.STATUS_ERROR, barcodes = {},
                           message = "Barcode found but unreadable (" .. entry.errors[1] .. ")" }
            else
                result = { status = Scanner.STATUS_NOT_FOUND, barcodes = {} }
            end
            LrFileUtils.delete(job.path)
        end
        results[i] = result
    end
    return results
end

local function makeJobs(photos)
    local jobs = {}
    for i, photo in ipairs(photos) do
        jobs[i] = { photo = photo, fileName = string.format("p%03d.jpg", i) }
    end
    return jobs
end

--[[
Scans a batch of photos (at most Scanner.batchSize) from Lightroom previews.
Returns a list parallel to `photos` of:
    { status = STATUS_*, barcodes = { { format =, text = }, ... }, message = "..." }
]]
function Scanner.scanBatch(photos, dir, previewSize)
    local jobs = makeJobs(photos)
    renderPreviews(jobs, previewSize)
    writePreviews(jobs, dir)
    return decodeJobs(jobs, dir, "Lightroom did not provide a preview")
end

-- Same as scanBatch, but from full-resolution renders (slower).
function Scanner.scanBatchFullSize(photos, dir)
    local jobs = makeJobs(photos)
    renderFullSize(jobs, dir)
    return decodeJobs(jobs, dir, "Lightroom did not render the photo")
end

-- Combines a preview result with a full-size rescan: barcodes from both are kept
-- (full-size first); a successful rescan clears an earlier read error.
function Scanner.mergeResults(preview, full)
    local barcodes, seen = {}, {}
    for _, list in ipairs { full.barcodes, preview.barcodes } do
        for _, barcode in ipairs(list) do
            local key = barcode.format .. "|" .. barcode.text
            if not seen[key] then
                seen[key] = true
                table.insert(barcodes, barcode)
            end
        end
    end
    if #barcodes > 0 then
        return { status = Scanner.STATUS_FOUND, barcodes = barcodes }
    end
    if full.status == Scanner.STATUS_NOT_FOUND and preview.status == Scanner.STATUS_NOT_FOUND then
        return full
    end
    return { status = Scanner.STATUS_ERROR, barcodes = {}, message = full.message or preview.message }
end

return Scanner
